feat: ci updates
whispir/whispir-java pull request #20
Opened 2023-02-13 23:06 UTC by mneri-whispir

* Currently the `test` task is being skipped, still trying to find out the difference between this and my testing on my personal repo.

2023-02-14 23:07 UTC, richardfontein requested changes

2023-02-14 23:07 UTC, richardfontein commented on package.json
> +}
I think we're best not to pollute the Java SDK with NodeJS files - we can instead simply run the following command in the CI workflow:
`npx -y @stoplight/prism-cli@^4.10.5 mock https://raw.githubusercontent.com/whispir/openapi/fix/prism-spec-update/openapi.yaml &`

2023-02-14 23:07 UTC, richardfontein commented on src/main/test/java/com/whispir/client/ApiClientTest.java
> +            System.out.println("Exception when calling MessagesApi#getMessageById");
The log here is not aligned with the operation - it should instead refer to failed Workspace call

2023-02-19 20:39 UTC, richardfontein requested changes

2023-02-19 20:39 UTC, richardfontein commented on .github/workflows/ci.yml
> +      # - uses: actions/checkout@v2
Got some commented code left here - can we remove?

2023-02-19 20:39 UTC, richardfontein commented on .github/workflows/ci.yml
> +        run: ./gradlew test
Got some redundant whitespace changes here - let's clean up to keep the PR diff clean

2023-02-19 20:39 UTC, richardfontein commented on .gitignore
> +.env
Got a whitespace change, let's also cleanup

2023-02-19 20:41 UTC, richardfontein commented
Hey @mneri-whispir , it's not clear why there are so many "File renamed without changes" committed files on the PR. Could you please elaborate?

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/32132657/219973988-dbcc2522-16a2-454e-b90c-8b20eecc0396.png">

2023-02-20 00:58 UTC, mneri-whispir commented
@richardfontein for the  "File renamed without changes", it's because of the location of these files. It's been moved from `src/main/test` to `src/test` so the test script would find the tests

2023-02-21 07:28 UTC, richardfontein approved these changes
LGTM!

2023-02-21 21:48 UTC, merged